import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

type Props = {};

const Home: NextPage<Props> = ({}) => {
	return (
		<div>
			<Head>
				<title>Firebase Authentication</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>Home</h1>
				<Link href="/login">Login</Link>
			</main>

			<footer></footer>
		</div>
	);
};

export default Home;
